# Generated by Django 5.2.2 on 2025-06-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Загрузите картинку')),
                ('description', models.TextField(verbose_name='Дайте описание')),
                ('type_book', models.CharField(choices=[('Short stories', 'Short stories'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'книгу',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
