# Generated by Django 5.2.2 on 2025-06-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio_recording',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube аудиокнигу', null=True),
        ),
    ]
