# Generated by Django 5.2.2 on 2025-06-12 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comment_review_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
