# Generated by Django 5.2.2 on 2025-06-16 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0007_remove_review_mark_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='basketmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('card_number', models.PositiveIntegerField(help_text='Введите номер карты (до 16 цифр)', validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
                ('status', models.CharField(choices=[('confirmed', 'Подтвержден'), ('not_confirmed', 'Не подтвержден')], default='not_confirmed', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
